### ISSUE TITLE
PinpointKit 1.0

### ISSUE THREAD

**Issue by irace** [Lickability/PinpointKit#6]
Off the top of my head, the various components that we’d need that can _not_ be extracted from Pinpoint.app would be:
- [ ] [Initialization/`UIWindow` gesture recognizer integration](https://github.com/Lickability/PinpointKit/issues/4)
- [ ] View controller traversal/presentation
- [ ] Launch view controller [design](https://github.com/Lickability/PinpointKit/issues/1) and development
- [ ] System log consumption
- [ ] [Delegate protocol design](https://github.com/Lickability/PinpointKit/issues/5)
